---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: "11.4.4"

suites:
- name: default
  run_list:
  - "recipe[apticron_test::default]"
  - "recipe[minitest-handler]"
  attributes:
    apticron:
      config:
        email: ["root", "admin@localhost"]
        diff_only: "1"
        listchanges_profile: "apticron"
        system: "test.example.dev"
        ipaddressnum: "2"
        notify_holds: "0"
        notify_new: "0"
        custom_subject: "[security updates] $SYSTEM: $NUM_PACKAGES package update(s)"
        custom_from: "sec@test.example.dev"
